import ProgressBar from "@ramonak/react-progress-bar";
import Dividers from "@mui/material/Divider";
import React from "react";

type Props = {};

const TrustIndex = (props: Props) => {
	return (
		<div className="bg-zinc-100 flex flex-col items-center mb-4 box-border drop-shadow-lg rounded-xl p-6 m-6 w-1/2 ">
			<div className="w-full mb-4">
				<h1 className="font-semibold text-lg pb-2">Trust Index</h1>

				<Dividers />
			</div>

			<div className="flex flex-col justify-between w-full">
				<h1 className="font-medium mb-2">Standard user rating</h1>
				<ProgressBar
					completed="70"
					customLabel="70/100"
					bgColor="#42b0f5"
					baseBgColor="white"
					labelAlignment="outside"
					width="90%"
					labelColor="black"
				/>
				<h1 className="font-medium text-sm italic pt-2 pb-4">
					This rating is generated by averaging the rating of premium
					users that has rated the post.
				</h1>
			</div>

			<div className="flex flex-col justify-between w-full">
				<h1 className="font-medium mb-2">Investigator rating</h1>
				<ProgressBar
					completed="60"
					customLabel="60/100"
					bgColor="#42f5e6"
					baseBgColor="white"
					labelAlignment="outside"
					width="90%"
					labelColor="black"
				/>
				<h1 className="font-medium text-sm italic pt-2 pb-4">
					This rating is generated by averaging the rating of all
					involed invesitagors.
				</h1>
			</div>

			<div className="flex flex-col justify-between w-full">
				<h1 className="font-medium mb-2">Jury rating</h1>
				<ProgressBar
					completed="50"
					customLabel="50/100"
					bgColor="#e0a848"
					baseBgColor="white"
					labelAlignment="outside"
					width="90%"
					labelColor="black"
				/>
				<h1 className="font-medium text-sm italic pt-2 pb-4">
					This rating is generated by averaging the rating of all
					involed juries.
				</h1>
			</div>

			<div className="flex flex-col justify-between w-full ">
				<h1 className="font-medium mb-2">Combined rating</h1>
				<ProgressBar
					completed="65"
					customLabel="65/100"
					bgColor="#21eb5a"
					baseBgColor="white"
					labelAlignment="outside"
					width="90%"
					labelColor="black"
				/>
				<h1 className="font-medium text-sm italic pt-2 pb-4">
					This rating is generated by combining all of three of the
					rating above. Users should always refer to this rating
					because it provides the most accurate result due to higher
					number of user involment.
				</h1>
				<div className="flex justify-around mt-4">
					<div className="flex flex-col justify-center items-center">
						<h1 className="text-red-500 font-semibold">0-30</h1>
						<h1 className="text-red-500 font-semibold">
							Untrusted
						</h1>
					</div>

					<div className="flex flex-col justify-center items-center">
						<h1 className="text-yellow-500 font-semibold">31-69</h1>
						<h1 className="text-yellow-500 font-semibold">
							Moderately Trusted
						</h1>
					</div>

					<div className="flex flex-col justify-center items-center">
						<h1 className="text-green-500 font-semibold">70-100</h1>
						<h1 className="text-green-500 font-semibold">
							Trusted
						</h1>
					</div>
				</div>
			</div>
		</div>
	);
};

export default TrustIndex;
